import React from 'react';
import Navbar from '../components/Navbar';
import { Footer } from '../components/Footer';

// A simple component for a feature card
const FeatureCard = ({ title, description }) => (
    <div className="bg-gray-800 p-6 rounded-2xl shadow-lg transform hover:scale-105 transition-transform duration-300">
        <h3 className="text-xl font-bold text-pink-400 mb-2">{title}</h3>
        <p className="text-gray-400">{description}</p>
    </div>
);

// Main App component for the About Page
export default function App() {
    return (
        <>
            <Navbar />
            <div className="flex items-center justify-center min-h-screen bg-black font-sans text-white">
                <div className="p-8 space-y-8 max-w-3xl w-full">
                    {/* --- Title --- */}
                    <div className="text-center">
                        <h1 className="text-5xl font-extrabold text-purple-600">About MagmaFitnessAI</h1>
                        <p className="text-gray-400 mt-2 text-lg">Your AI-Powered Fitness Companion</p>
                    </div>

                    {/* --- Our Mission Section --- */}
                    <div className="space-y-4 text-center">
                        <h2 className="text-3xl font-bold text-purple-600">Our Mission</h2>
                        <p className="text-gray-300 leading-relaxed">
                            At MagmaFitnessAI, our mission is to make fitness accessible, personal, and intelligent for everyone. We believe that achieving your health goals shouldn't be a guessing game. By leveraging the power of cutting-edge AI, we provide you with the tools and insights you need to build a stronger, healthier you.
                        </p>
                    </div>

                    {/* --- What We Offer Section --- */}
                    <div className="space-y-4">
                        <h2 className="text-3xl font-bold text-purple-600 text-center">What We Offer</h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4">
                            <FeatureCard
                                title="Personalized AI Plans"
                                description="Get a complete fitness and diet plan tailored to your body, goals, and preferences, generated by our advanced AI coach."
                            />
                            <FeatureCard
                                title="Suite of Calculators"
                                description="Utilize a wide range of calculators for everything from BMI and Body Fat to estimating your one-rep max for key lifts."
                            />
                            <FeatureCard
                                title="Strength Standards"
                                description="Compare your lifts against established standards for your bodyweight and experience level to track your progress effectively."
                            />
                            <FeatureCard
                                title="Sleek & Simple Interface"
                                description="Enjoy a clean, intuitive, and dark-themed user interface that makes navigating your fitness journey a pleasure."
                            />
                        </div>
                    </div>

                    {/* --- Our Technology Section --- */}
                    <div className="space-y-4 text-center">
                        <h2 className="text-3xl font-bold text-purple-600">Our Technology</h2>
                        <p className="text-gray-300 leading-relaxed">
                            This project is built on a modern tech stack to deliver a fast and responsive experience. We use <strong className="text-purple-400">Next.js</strong> and <strong className="text-purple-400">React</strong> for the frontend, styled with <strong className="text-purple-400">Tailwind CSS</strong>. The intelligent core of our application is powered by <strong className="text-purple-400">Google's Gemini AI</strong>, which allows us to generate the highly personalized and detailed fitness plans that set us apart.
                        </p>
                    </div>

                </div>
            </div>
            <Footer />
        </>
    );
}
